name: Teste APK com Maestro Framework

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      # 🔥 Cache Android (ganho grande de tempo)
      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.android
            /usr/local/lib/android
          key: android-${{ runner.os }}

      - name: Instalar ADB
        run: |
          sudo apt-get update
          sudo apt-get install -y adb

      - name: Instalar Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      # 🚀 Emulator + execução com mais controle
      - name: Rodar emulador + testes
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 6
          emulator-options: >
            -no-window
            -no-audio
            -no-boot-anim
            -gpu swiftshader_indirect
          disable-animations: true
          script: |
            echo "Aguardando device..."
            adb wait-for-device

            echo "Garantindo boot completo..."
             until [ "$BOOT_COMPLETED" = "1" ] || [ $elapsed -ge $timeout ]; do
                BOOT_COMPLETED=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
                echo "Aguardando boot... ($BOOT_COMPLETED)"
                sleep 2
                elapsed=$((elapsed+2))
              done
              
              if [ "$BOOT_COMPLETED" != "1" ]; then
                echo "Emulator não iniciou corretamente"
                exit 1
              fi

            echo "Desbloqueando tela..."
            adb shell input keyevent 82

            echo "Instalando APK..."
            adb install qafoodTest.apk

            echo "Rodando testes Maestro..."
            maestro test .maestro/

      # 📸 Logs e evidências (ESSENCIAL pra debug)
      - name: Upload de artifacts
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: maestro-artifacts
          path: |
            ~/.maestro/tests/
