name: Teste APK com Maestro Framework

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3
      
      - name: Instalar ADB
        run: |
          sudo apt-get update
          sudo apt-get install -y adb

      - name: Instalar Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Iniciar emulador Android
        run: |
           docker run -d \
            -p 5554:5554 \
            -p 5555:5555 \
            budtmo/docker-android:emulator_11.0

      - name: Esperar emulador iniciar
        run: |
           adb connect localhost:5555
            # tenta várias vezes até conectar
            for i in {1..10}; do
              adb devices
              if adb devices | grep -q "device$"; then
                echo "Emulador conectado!"
                break
              fi
              echo "Aguardando emulador..."
              sleep 10
            done

      - name: Instalar APK
        run: |
          adb install qafoodTest.apk

      - name: Rodar testes Maestro
        run: |
          maestro test .maestro/
